name: Build and deploy (pygbag -> gh-pages)

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install pygbag

      - name: Build web bundle with pygbag
        # Try a couple of pygbag invocation styles to be resilient across versions
        run: |
          set -e
          python -m pygbag build project.py web || true
          python -m pygbag project.py web || true
          pygbag project.py web || true

      - name: Copy assets to web bundle (ensures images/sounds are available)
        run: |
          if [ -d assets ]; then
            cp -R assets web/ || true
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./web
